name: 'Validate linked work item'

on: 
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
  pull_request_target:
    types: 
      - opened
      - reopened
      - synchronize

permissions:
    pull-requests: write
    issues: write

    
jobs:
  create-edit-comment:
    name: check   
    runs-on: ubuntu-latest
    steps:
      - uses: cosmoconsult/github-actions-pr-is-linked-to-work-item@3c24859b3730aaea345fe954df293f9656555f40
